### ISSUE TITLE
Deprecated curly braces in view-user-privilege-level.php

### ISSUE THREAD

**Issue by issolahma** [webpwnized/mutillidae-docker#1]
Hi,
You don't have issues on the main repo so I post here.
On line 6 and 102 of view-user-privilege-level.php file curly braces are used but it's deprecated and return an error (CBC flip-bit challenge).
The error (with the docker install): `Array and string offset access syntax with curly braces is no longer supported`
Thank you

**Comment by webpwnized** [comment]
I didnt see a PR, so I patched it and pushed a new version 2.8.60
