### ISSUE TITLE
Stuck on GET parameter 'page' does not appear to be dynamic

### ISSUE THREAD

**Issue by calwa** [webpwnized/mutillidae-docker#12]
Have tried on 2 different Kali hosts and getting the same issue:

[*] starting @ 19:57:44 /2022-10-08/

[19:57:44] [INFO] testing connection to the target URL
[19:57:44] [WARNING] there is a DBMS error found in the HTTP response body which could interfere with the results of the tests
you have not declared cookie(s), while server wants to set its own ('PHPSESSID=qoijh8f8rh3...icq6o4eka3;showhints=1'). Do you want to use those [Y/n] 
[19:57:45] [INFO] checking if the target is protected by some kind of WAF/IPS
[19:57:45] [INFO] testing if the target URL content is stable
[19:57:46] [INFO] target URL content is stable
[19:57:46] [INFO] testing if GET parameter 'page' is dynamic
[19:58:16] [CRITICAL] connection timed out to the target URL. sqlmap is going to retry the request(s)
[19:59:46] [WARNING] GET parameter 'page' does not appear to be dynamic
[20:00:16] [CRITICAL] connection timed out to the target URL. sqlmap is going to retry the request(s)
[20:01:46] [CRITICAL] connection timed out to the target URL

[*] ending @ 20:01:46 /2022-10-08/

----------------------

www                | <br />
www                | <b>Deprecated</b>:  Directive 'allow_url_include' is deprecated in <b>Unknown</b> on line <b>0</b><br />
www                | <br />
www                | <b>Deprecated</b>:  Directive 'allow_url_include' is deprecated in <b>Unknown</b> on line <b>0</b><br />
www                | <br />
www                | <b>Deprecated</b>:  Directive 'allow_url_include' is deprecated in <b>Unknown</b> on line <b>0</b><br />
www                | <br />
www                | <b>Deprecated</b>:  Directive 'allow_url_include' is deprecated in <b>Unknown</b> on line <b>0</b><br />

**Comment by webpwnized** [comment]
I tested the lab on Mutillidae 2.10.6 and it works well.

The output shows SQLmap lost connectivity to the website, so could not continue. Depending on how Mutillidae is deployed, the site might be protected by a WAF or there may be other issues that caused the connection to be disrupted. In any case, please determine why the application became unavailable. 

**_[19:58:16] [CRITICAL] connection timed out to the target URL. sqlmap is going to retry the request(s)_**

**Comment by devzerker** [comment]
Faced with the same problem. But it is not a sqlmap problem. The reason of why sqlmap hangs is mutillidae blocks any requests for a while after not existence page is requested. For example: when i run the following command
`sqlmap -u "http://localhost/index.php?page=login.php" --data="username=*&password=*&login-php-submit-button=Login"`
sqlmap interprets query parameter `page` as candidate for injecting and send requests like `http://localhost/index.php?page=blahblah`

If you try to open `http://localhost/index.php?page=blahblah` manually in browser it hangs too.

Tested on `ubuntu 22.04` and `kali 2022.3`, sqlmap . Step to reproduce:
1. Clone this repo
2. Run `docker compose up --build` in cloned repo
3. Run open `http://localhost/index.php?page=blahblah` in browser, the request will hangs and any other request will hang too.

Workaround is define in command the parameter you want sqlmap to test for injecting, for example `username`:
`sqlmap -u "http://localhost/index.php?page=login.php" --data="username=*&password=*&login-php-submit-button=Login" -p username`

**Comment by webpwnized** [comment]
Defining the target parameter with "-p" is the best practice.

**Comment by devzerker** [comment]
> Defining the target parameter with "-p" is the best practice.

IMO hanging all requests for a while when non existence page was requested is not right behavior. In all guides i saw mutillidae returns 404 instantly. I think there are other tools besides sqlmap that rely on instant request and all newbies will hurt trying to explore mutillidae, like me.

**Comment by webpwnized** [comment]
> > Defining the target parameter with "-p" is the best practice.
> 
> IMO hanging all requests for a while when non-existence page was requested is not right behavior. In all guides i saw mutillidae returns 404 instantly. I think there are other tools besides sqlmap that rely on instant request and all newbies will hurt trying to explore mutillidae, like me.

1. 2. The comment about using "-p" is unrelated to the possible issue of the browser hanging. @calwa asked about the SQLMap lab. In the lab, using "-p" is the best answer regardless of the browser hanging issue. (Please note my browser is not hanging. I could not reproduce @calwa issue, but using -p gets back on track to finish the lab)
3. I cannot reproduce the issue experienced by @devzerker. Please see the screenshot below. I tested with mutillidae-docker and with mutillidae-dockerhub projects for good measure. 
4. @devzerker is obviously having an issue and as he indicated. It's likely the same issue affecting @calwa. If you determine the issue, please submit a Pull Request. I will either accept the PR or use the information to improve the project in a new release.

![image](https://user-images.githubusercontent.com/12465192/198888916-a7dac907-408f-46c2-82d9-a71f07b2c44b.png)
