### ISSUE TITLE
Add database creation disclaimer

### ISSUE THREAD

**Issue by nicovell3** [webpwnized/mutillidae-docker#16]
When setting up the docker compose environment for the first time, the database "mutillidae" cannot be accessed and reports an error. It would be ideal if a disclaimer like "Use the option to recreate the database the first the web interface is displayed" was included in the README.md, just after the `docker compose up -d` command in the TLDR section.

I reviewed the database docker logs and the Dockerfile, which do not make any kind of reference to the "mutillidae" database, before realizing the error in the web interface provides the utility to create the database:

![image](https://github.com/webpwnized/mutillidae-docker/assets/9163055/ac454a57-4a25-4520-8c87-192785e80613)

**Comment by webpwnized** [comment]
Good suggestion. Did you fix the readme with a PR?

**Comment by nicovell3** [comment]
@webpwnized I've just created it 👌
Thank you very much for your job!

**Comment by webpwnized** [comment]
Thank you for the PR
